services:
  postgres:
    container_name: postgres
    image: "postgres:latest"
    environment:
      - "POSTGRES_DB=mydatabase"
      - "POSTGRES_PASSWORD=secret"
      - "POSTGRES_USER=myuser"
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # entrypoint: ./db/entrypoint.sh
    # volumes:
    #   - ./db:/docker-entrypoint-initdb.d
    # entrypoint: ./db/data.sql

  pgadmin:
    container_name: pgadmin_api_test
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"

volumes:
  postgres_data:
  pgadmin_data:
